name: HTML5 Validation
on: push

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - name: HTML5Validator
      uses: Cyb3r-Jak3/html5validator-action@0.6.1
      with:
        root: tests/
        blacklist: invalid
